### ISSUE TITLE
Can't quite figure out the setup

### ISSUE THREAD

**Issue by macxcool** [Brawl345/FreshRSS-Checker#15]
I followed the instructions in the setup and set my API password etc. Then I entered my URL (I assume this is the base URL, as in http://domain/freshrss (I have freshrss in a folder)?), but I still get ERR as the badge. What am I missing?

Very cool addon, btw. I just started self-hosting RSS with FreshRSS after The Old Reader added big ads. ;-)

**Comment by Brawl345** [comment]
You need the base URL of FreshRSS, so the URL to the folder if you installed in in a folder. The addon appends `/api/fever.php` to the URL (see if it works in the browser). Also try checking the status of the API on `/api/`, there you can also see the Fever compatible API URL and status. Plus you need to use the API password under Profile (the very last input field).

**Comment by macxcool** [comment]
Your adding /api/fever.php tipped me off to the solution. I had to do domain/freshrss/p for it to work. I found out yesterday that my install uses /p/api. I didn't tell it to, but it does. ;-)
It's working now.  Thanks for the tip.
