### ISSUE TITLE
FreshRSS URL Error Fix

### ISSUE THREAD

**Issue by Avasond** [Brawl345/FreshRSS-Checker#16]
An "ERR" label is returned for some users in Chrome setting the FreshRSS URL to:
`https://rss.example.com/`
Error is resolved when changing FreshRSS URL to:
`https://rss.example.com/p/`

I do not know if this is a security issue in some Chrome instances or an issue with FreshRSS changing their URL hierarchy, but this solves the problem!

**Comment by Brawl345** [comment]
It depends on your setup. The add-on appends `/api/fever.php` to the URL so just make sure it's accessible there. In my setup I don't need the `/p/`. See also #15.

EDIT: I will pin the issue so that everyone sees it.

**Comment by Avasond** [comment]
Thank you! I apologize for not looking at the resolved issues, GH defaults to is:open for me so I missed it.

Although, I think mentioning how the parser behaves in your readme (and linking the readme in your webstore app) would clear it up for most folks faster than checking the issues.
