### ISSUE TITLE
URL-Error shown in toolbar (Firefox 132 / Arch Linux)

### ISSUE THREAD

**Issue by actionpapst** [Brawl345/FreshRSS-Checker#17]
Hey there,

I added an icon to my toolbar in Firefox some months ago. At some point it started giving me the "Err" label instead of the number of unread items.

Some things worth mentioning here: 

I block cross-site cookies and isolate others with Firefox. Is that a problem? It seemed to have made no difference when I changed that setting.

Cookies are thrown away after closing firefox. I specifically whitelisted the domain and the subdomain of my FreshRSS instance. 

The extension has all the permissions needed: "read the domain" and "read all websites data".

Is there a way I can sort of debug the extension?

**Comment by Brawl345** [comment]
Hi, thanks for using FreshRSS Checker!

I only use the stock settings so I can only guess. The add-on doesn't use cookies though, it only sends the login data to your domain. You can go to about:debugging#/runtime/this-firefox and click on the "Inspect" button for the add-on which pops up the devtools. In the console you can see any errors that might happen. When you leave that open and right-click the addon -> "Check now" you can also see the network request and if something is blocking it and if it can read your options.

In the settings for FreshRSS Checker, do you also see your domain at the bottom? Normally you don't need the "Access all websites" permission, only the host permission for your domain.

**Comment by actionpapst** [comment]
Interesting: The console shows no errors, but `[HTTP/2 200  19ms]` which looks as if everything was okay.

`curl https://domain.tld/api/fever.php` answers correctly with `{"api_version":3,"auth":0}`

The login data is correct and I checked everything multiple times.

**Comment by Brawl345** [comment]
What is the answer of the "Check now" request in the network console? It should contact `https://domain.tld/api/fever.php?api&unread_item_ids` and the response should be something like:

```
{"api_version":3,"auth":1,"last_refreshed_on_time":1731291006,"unread_item_ids":""}
```

**Comment by actionpapst** [comment]
Alright. The response is the same I posted before when I just use curl: `{"api_version":3,"auth":0}` which may indicate that my login is broken in some way.

When I open up the runtime debugger FreshRSS-Checker has a yellow warning attached to it: _Reading manifest: Warning processing background.service_worker: An unexpected property was found in the WebExtension manifest._

Thanks for your help :)

**Comment by Brawl345** [comment]
Yeah there seems to be something wrong with your login. Make sure you use your API password, not your regular password. You can set it in your FreshRSS profile at the bottom.

About the warning:

```
Warning processing background.service_worker: An unexpected property was found in the WebExtension manifest.
```

That is expected because this key is only supported on Chromium browsers and I'm using the same Manifest for both browsers. It can safely be ignored.

**Comment by actionpapst** [comment]
Oh, shit. I guess I must have messed up the two passwords when setting up the extension on this machine. It works now. Thanks again for your help.

**Comment by Brawl345** [comment]
No problem, glad it works now!
